<a href="https://colab.research.google.com/github/UtkarshRasal/deep_learning/blob/master/tensor_math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Maths

* Addition, subtraction, multiply, divide, remainders,
* Shorthand and LongHand
* Reassignment

In [29]:
import torch
import numpy as np

In [32]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

### Addition

In [33]:
# Addition shorthand
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [34]:
# addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [56]:
# Another addition Longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

### Subtraction

In [35]:
# subtraction shorthand
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [39]:
# Subtraction longhand
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [57]:
# Another subtraction longhand
tensor_a.sub(tensor_b)

tensor([-4, -4, -4, -4])

### Multiplication

In [41]:
# Multiplication shorthand
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [43]:
# Multiplication longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [58]:
# Another multiplication longhand
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

### Division

In [45]:
# Division shorthand
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [47]:
# division longhand
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [59]:
# Another Division Longhand
tensor_a.div(tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

### Remainders

In [50]:
# Remainder shorthand
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [51]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [61]:
# Another remianders longhand
tensor_b.remainder(tensor_a)

tensor([0, 0, 1, 0])

### Exponents

In [53]:
# Exponents shorthand
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [54]:
# exponents longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [63]:
# Another longhand exponents
tensor_a.pow(tensor_b)

tensor([    1,    64,  2187, 65536])

## Reassignment (_)

it means assigning the value to the same variable again, similar to doing a = a + b

In [67]:
tensor_a.add_(tensor_b) # the underscore after add is responsible for reassignment

tensor([11, 14, 17, 20])

In [68]:
tensor_a # calculated value is assigned to tensor_a

tensor([11, 14, 17, 20])

In [70]:
torch.add_(tensor_a, tensor_b) # Will give an error because reassignment doesn't work in this way

AttributeError: module 'torch' has no attribute 'add_'

In [71]:
# Reassignment will work for all functions for sub, mul, div and all

In [ ]:
# tensor_a.sub_(tensor_b)
# tensor_a.mul_(tensor_b)
# tensor_a.div_(tensor_b)
# tensor_a.remainder_(tensor_b)
# tensor_a.exponents_(tensor_b)