<a href="https://colab.research.google.com/github/UtkarshRasal/deep_learning/blob/master/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# starting with tensors

### Tensors


*   Tensor is a specialized multidimensional array
*   default datatype is float32
*   Very similar to numpy arrays but with are good for higher computational efficieny





In [11]:
import torch, numpy as np

In [6]:
tensor_2d = torch.randn(3,4) # will create a 2 dimensional array with 3 rows and 4 columns

In [7]:
tensor_2d

tensor([[ 0.5578, -0.1357,  0.9486,  2.4311],
        [ 0.8154, -0.8178,  1.6905, -0.0900],
        [ 0.5434, -0.3292,  1.4527, -1.0265]])

In [9]:
tensor_3d = torch.zeros(2,3,4) # this will create a 3 dimensional array, torch.zeros is just to create tensors containing only '0's

In [10]:
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
# create tensors using numpy arrays
np1 = np.random.rand(3,4)
np1

array([[0.16267144, 0.28915764, 0.19721475, 0.79016832],
       [0.3107467 , 0.49779786, 0.5021194 , 0.57993486],
       [0.41795211, 0.7114    , 0.64200627, 0.46922821]])

In [16]:
my_tensors = torch.tensor(np1)
my_tensors

tensor([[0.1627, 0.2892, 0.1972, 0.7902],
        [0.3107, 0.4978, 0.5021, 0.5799],
        [0.4180, 0.7114, 0.6420, 0.4692]], dtype=torch.float64)

In [17]:
# another way for doing the same thing
my_tensors = torch.from_numpy(np1)
my_tensors

tensor([[0.1627, 0.2892, 0.1972, 0.7902],
        [0.3107, 0.4978, 0.5021, 0.5799],
        [0.4180, 0.7114, 0.6420, 0.4692]], dtype=torch.float64)