<a href="https://colab.research.google.com/github/UtkarshRasal/deep_learning/blob/master/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Ops

In [2]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## reshape and view

In [4]:

my_torch = my_torch.reshape(2,5) #changing the shape of tensors like going from 1-D to 2-D
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
my_torch = my_torch.reshape(2,6) # we will get an error because the reshaping will not be proper because in 10 items you can't split the data into 2 rows and 6 columns

RuntimeError: shape '[2, 6]' is invalid for input of size 10

### reshape using -1, if we don't know the numbers of items

In [6]:

my_tensors = torch.arange(10)
my_tensors

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
reshaped_tensors = my_tensors.reshape(2, -1)
reshaped_tensors


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
reshaped_tensors = my_tensors.reshape(3, -1) # again this error because we cannot split data of 10 tensors in 3 rows
reshaped_tensors

RuntimeError: shape '[3, -1]' is invalid for input of size 10

In [9]:
reshaped_tensors = my_tensors.reshape(2, -1)
reshaped_tensors

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
reshaped_tensors = my_tensors.reshape(-1, 2)
reshaped_tensors

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

### when a value changes in the original tensor then it will be reflected in the reshaped tensor

In [11]:
original_tensor = torch.arange(10)
original_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
reshaped_tensor = original_tensor.reshape(2,5)
reshaped_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
original_tensor[2] =71298
original_tensor

tensor([    0,     1, 71298,     3,     4,     5,     6,     7,     8,     9])

In [14]:
reshaped_tensor # value was updated in original tensor, but is reflecting in reshaped tensor as well

tensor([[    0,     1, 71298,     3,     4],
        [    5,     6,     7,     8,     9]])

## Slices

In [15]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_torch[7] # grab a specific item

tensor(7)

In [17]:
# slice items from tensors
my_reshaped_torch = my_torch.reshape(5,2)
my_reshaped_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [18]:
# to fetch only second columns items i.e., 1,3,5,7,9
my_reshaped_torch[:, 1] # ':' -> we can add range from where to where we need to fetch, and the next parameter '1' tells the index of the column

tensor([1, 3, 5, 7, 9])

In [19]:
my_reshaped_torch[1:4, 1] #  ':' -> we can add range from where to where we need to fetch, and the next parameter '1' tells the index of the column

tensor([3, 5, 7])

In [20]:
# return column of the tensor(my_reshaped_torch)

In [21]:
my_reshaped_torch[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

## Matrix Multiplication

In [22]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [23]:
tensor * tensor # element wise multiplcation, column to column will be multiplied

tensor([1, 4, 9])

In [24]:
tensor @ tensor # in matrix multiplcation dot product will be done on both tensors => 1*1 + 2*2 + 3*3 = 14. And result of a vector @ vector matrix multiplication will be scaler

tensor(14)

In [15]:
# matrix multiplication
import torch
tensor_a = torch.tensor([[1,2], [3,4], [5,6]])
tensor_b = torch.tensor([[7,10], [8,11], [9,12]])

In [16]:
torch.matmul(tensor_a, tensor_b) # will give and error because of the shape

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [18]:
torch.matmul(tensor_a, tensor_b.T) # we will have to matrix transpose to change the shape of a tensor

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [21]:
# short hand for torch.matmul is torch.mm
torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])