<a href="https://colab.research.google.com/github/UtkarshRasal/deep_learning/blob/master/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Ops

In [9]:
import torch

In [10]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## reshape and view

In [11]:

my_torch = my_torch.reshape(2,5) #changing the shape of tensors like going from 1-D to 2-D
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch = my_torch.reshape(2,6) # we will get an error because the reshaping will not be proper because in 10 items you can't split the data into 2 rows and 6 columns

RuntimeError: shape '[2, 6]' is invalid for input of size 10

### reshape using -1, if we don't know the numbers of items

In [13]:

my_tensors = torch.arange(10)
my_tensors

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
reshaped_tensors = my_tensors.reshape(2, -1)
reshaped_tensors


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
reshaped_tensors = my_tensors.reshape(3, -1) # again this error because we cannot split data of 10 tensors in 3 rows
reshaped_tensors

RuntimeError: shape '[3, -1]' is invalid for input of size 10

In [ ]:
reshaped_tensors = my_tensors.reshape(2, -1)
reshaped_tensors

In [16]:
reshaped_tensors = my_tensors.reshape(-1, 2)
reshaped_tensors

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

### when a value changes in the original tensor then it will be reflected in the reshaped tensor

In [17]:
original_tensor = torch.arange(10)
original_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
reshaped_tensor = original_tensor.reshape(2,5)
reshaped_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
original_tensor[2] =71298
original_tensor

tensor([    0,     1, 71298,     3,     4,     5,     6,     7,     8,     9])

In [20]:
reshaped_tensor # value was updated in original tensor, but is reflecting in reshaped tensor as well

tensor([[    0,     1, 71298,     3,     4],
        [    5,     6,     7,     8,     9]])

## Slices

In [21]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
my_torch[7] # grab a specific item

tensor(7)

In [23]:
# slice items from tensors
my_reshaped_torch = my_torch.reshape(5,2)
my_reshaped_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [24]:
# to fetch only second columns items i.e., 1,3,5,7,9
my_reshaped_torch[:, 1] # ':' -> we can add range from where to where we need to fetch, and the next parameter '1' tells the index of the column

tensor([1, 3, 5, 7, 9])

In [25]:
my_reshaped_torch[1:4, 1] #  ':' -> we can add range from where to where we need to fetch, and the next parameter '1' tells the index of the column

tensor([3, 5, 7])

In [ ]:
# return column of the tensor(my_reshaped_torch)

In [27]:
my_reshaped_torch[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])