<a href="https://colab.research.google.com/github/UtkarshRasal/deep_learning/blob/master/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# starting with tensors

### Tensors


*   Tensor is a specialized multidimensional array
*   default datatype is float32
*   Very similar to numpy arrays but with are good for higher computational efficieny





In [3]:
import torch, numpy as np

In [4]:
tensor_2d = torch.randn(3,4) # will create a 2 dimensional array with 3 rows and 4 columns

In [5]:
tensor_2d

tensor([[ 0.9818, -0.3611, -1.2323,  0.1980],
        [ 0.1681, -1.2922,  0.4425,  0.6587],
        [ 0.1248, -1.0478,  0.2641,  0.6748]])

In [6]:
tensor_3d = torch.zeros(2,3,4) # this will create a 3 dimensional array, torch.zeros is just to create tensors containing only '0's

In [7]:
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
# create tensors using numpy arrays
np1 = np.random.rand(3,4)
np1

array([[0.19126585, 0.2272485 , 0.51245808, 0.9863589 ],
       [0.6242306 , 0.55419874, 0.52415205, 0.92251361],
       [0.05590119, 0.30703897, 0.78282762, 0.81560271]])

In [9]:
my_tensors = torch.tensor(np1)
my_tensors

tensor([[0.1913, 0.2272, 0.5125, 0.9864],
        [0.6242, 0.5542, 0.5242, 0.9225],
        [0.0559, 0.3070, 0.7828, 0.8156]], dtype=torch.float64)

In [10]:
# another way for doing the same thing
my_tensors = torch.from_numpy(np1)
my_tensors

tensor([[0.1913, 0.2272, 0.5125, 0.9864],
        [0.6242, 0.5542, 0.5242, 0.9225],
        [0.0559, 0.3070, 0.7828, 0.8156]], dtype=torch.float64)

### check the dimension of tensor using ndim

In [19]:
# scaler
scaler_tensor = torch.tensor(7) # 0 dimensional vector OR scaler
print(f"{scaler_tensor} - {scaler_tensor.ndim} dimensional")

7 - 0 dimensional


In [20]:
# One dimensional array
one_tensor = torch.tensor([1, 2, 3, 4])
print(f"{one_tensor} - {one_tensor.ndim} dimensional")

tensor([1, 2, 3, 4]) - 1 dimensional


In [22]:
# 2 dimensional array
two_tensor = torch.randn(2,4)
print(f"{two_tensor} - {two_tensor.ndim} dimensional")

tensor([[ 0.8701,  1.3223, -0.6874, -0.8265],
        [-0.1282, -0.4565, -0.2253, -0.3930]]) - 2 dimensional


In [23]:
# 3 dimensional array
three_tensor = torch.randn(2,4, 1)
print(f"{three_tensor} - {three_tensor.ndim} dimensional")

tensor([[[-0.6445],
         [ 1.4866],
         [-0.2101],
         [-0.5722]],

        [[-0.5681],
         [-1.2543],
         [ 0.6865],
         [-0.9128]]]) - 3 dimensional


### Retrieve integer value from scaler tensor

In [25]:
scaler_tensor = torch.tensor(5)
scaler_tensor

tensor(5)

In [26]:
scaler_tensor.item() # will return the integer value from a single tensor. Only works with single tensor

5

In [28]:
torch.tensor(5).ndim

0

## Range


In [45]:
new_tensor = torch.arange(1, 10,1)
new_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensor Like

In [47]:
new_tensor.size()


torch.Size([9])